import { useState, useEffect } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../lib/api'

type NotifPrefs = {
  nudge_enabled: boolean
  nudge_hour: number
  nudge_tz: string
  recap_enabled: boolean
  health_alerts_enabled: boolean
}

type SwState = 'checking' | 'installing' | 'ready' | 'failed'

// Generated by vite-plugin-pwa (injectManifest, filename: sw.ts) at the root scope.
const SW_URL = '/sw.js'

function urlBase64ToUint8Array(base64String: string): Uint8Array<ArrayBuffer> {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = atob(base64)
  return Uint8Array.from([...rawData].map((c) => c.charCodeAt(0)))
}

function isTrustedPwaOrigin(): boolean {
  return window.location.protocol === 'https:' &&
    !['localhost', '127.0.0.1'].includes(window.location.hostname)
}

// Resolve an *active* service worker registration without relying solely on
// navigator.serviceWorker.ready, which hangs indefinitely on iOS standalone
// PWAs after a reinstall. We wait on the registration object register() hands
// back (getRegistration() can transiently return null on some browsers and
// never surface the worker we just kicked off) and resolve the moment its
// worker reaches 'activated' — driven by statechange events, with a poll
// backstop for iOS where those events fire unreliably.
//
// The timeout is generous because the very first install precaches the app
// shell (several MB); on a cold cache that can take much longer than a few
// seconds, and a premature throw here is exactly what made "Subscribe" fail on
// desktop even though the worker was still legitimately activating.
async function getReadyRegistration(timeoutMs = 60000): Promise<ServiceWorkerRegistration> {
  let reg: ServiceWorkerRegistration | undefined
  if (isTrustedPwaOrigin()) {
    // Do NOT catch — if register() throws (wrong MIME, security error, bad URL)
    // we want to surface that error rather than wait the full timeout.
    reg = await navigator.serviceWorker.register(SW_URL)
  } else {
    reg = (await navigator.serviceWorker.getRegistration()) ?? undefined
  }

  if (reg?.active) return reg

  return new Promise<ServiceWorkerRegistration>((resolve, reject) => {
    let settled = false
    let tracked: ServiceWorker | null = null

    const finish = (fn: () => void) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      clearInterval(poll)
      reg?.removeEventListener('updatefound', onUpdateFound)
      tracked?.removeEventListener('statechange', onStateChange)
      fn()
    }

    const checkActive = (): boolean => {
      if (reg?.active) {
        finish(() => resolve(reg as ServiceWorkerRegistration))
        return true
      }
      return false
    }

    const onStateChange = () => {
      if (tracked?.state === 'redundant') {
        finish(() => reject(new Error('Background service failed to install. Reload the page and try again.')))
        return
      }
      checkActive()
    }

    const track = (worker: ServiceWorker | null) => {
      if (!worker || worker === tracked) return
      tracked?.removeEventListener('statechange', onStateChange)
      tracked = worker
      tracked.addEventListener('statechange', onStateChange)
      onStateChange()
    }

    const onUpdateFound = () => track(reg?.installing ?? reg?.waiting ?? null)

    const timer = setTimeout(
      () => finish(() => reject(new Error('Background service is still preparing — leave this page open a few seconds and tap Subscribe again.'))),
      timeoutMs,
    )

    // iOS backstop: statechange/updatefound can fail to fire after a PWA
    // reinstall, so also re-read the registration on an interval.
    const poll = setInterval(async () => {
      if (checkActive()) return
      const latest = await navigator.serviceWorker.getRegistration().catch(() => null)
      if (latest) { reg = latest; track(latest.installing ?? latest.waiting ?? null); checkActive() }
    }, 750)

    if (!reg) {
      finish(() => reject(new Error('Background service unavailable. Reload the page and try again.')))
      return
    }
    reg.addEventListener('updatefound', onUpdateFound)
    track(reg.installing ?? reg.waiting ?? null)
    checkActive()
    // .ready resolves on activation; on iOS it can hang, so it only races the
    // timeout/poll — it never gates resolution on its own.
    navigator.serviceWorker.ready.then((r) => finish(() => resolve(r))).catch(() => {})
  })
}

const HOUR_OPTIONS = Array.from({ length: 24 }, (_, i) => {
  const h = i % 12 === 0 ? 12 : i % 12
  const period = i < 12 ? 'am' : 'pm'
  return { value: i, label: `${h}:00 ${period}` }
})

export function NotificationsCard() {
  const queryClient = useQueryClient()
  const [subscribed, setSubscribed] = useState(false)
  const [permissionState, setPermissionState] = useState<NotificationPermission>(
    () => ('Notification' in window ? Notification.permission : 'default')
  )
  const [statusMsg, setStatusMsg] = useState<string | null>(null)
  const [localTz, setLocalTz] = useState<string | null>(null)
  const [swState, setSwState] = useState<SwState>(
    () => (!('serviceWorker' in navigator) ? 'failed' : 'checking')
  )
  const [swStuck, setSwStuck] = useState(false)
  const [pending, setPending] = useState(false)

  const { data: prefs } = useQuery<NotifPrefs>({
    queryKey: ['notifications', 'preferences'],
    queryFn: () => api.get('/notifications/preferences'),
  })

  const { data: vapidData } = useQuery<{ public_key: string }>({
    queryKey: ['notifications', 'vapid-key'],
    queryFn: () => api.get('/notifications/vapid-public-key'),
  })

  const vapidKey = vapidData?.public_key ?? null

  // Track SW readiness by polling getRegistration() rather than awaiting
  // navigator.serviceWorker.ready (which hangs on iOS standalone PWAs). Polling
  // stops as soon as a worker is active.
  useEffect(() => {
    if (!('serviceWorker' in navigator)) return

    let cancelled = false
    let timer: ReturnType<typeof setTimeout> | undefined

    const poll = async () => {
      if (cancelled) return
      const reg = await navigator.serviceWorker.getRegistration().catch(() => null)
      if (cancelled) return
      if (reg?.active) {
        setSwState('ready')
        reg.pushManager.getSubscription()
          .then((sub) => { if (!cancelled) setSubscribed(!!sub) })
          .catch(() => {})
        return
      }
      setSwState(reg?.installing || reg?.waiting ? 'installing' : 'checking')
      timer = setTimeout(poll, 1500)
    }
    poll()

    // Watch for OS-level permission changes so the UI updates without a reload.
    let permStatus: PermissionStatus | null = null
    const onPermChange = () => {
      if (!permStatus) return
      setPermissionState(
        permStatus.state === 'granted' ? 'granted'
          : permStatus.state === 'denied' ? 'denied'
          : 'default'
      )
    }
    if ('permissions' in navigator) {
      navigator.permissions.query({ name: 'notifications' as PermissionName }).then((status) => {
        if (cancelled) return
        permStatus = status
        status.addEventListener('change', onPermChange)
      }).catch(() => {})
    }

    return () => {
      cancelled = true
      if (timer) clearTimeout(timer)
      permStatus?.removeEventListener('change', onPermChange)
    }
  }, [])

  // Surface a "close and reopen" hint if the SW never activates within 25 s.
  // setSwStuck(true) is inside a setTimeout callback so it does not trigger cascading renders.
  // setSwStuck(false) is not needed: swStuck is only shown when swPreparing is true, which is
  // already false when swState === 'ready'.
  useEffect(() => {
    if (swState === 'ready') return
    const t = setTimeout(() => setSwStuck(true), 25_000)
    return () => clearTimeout(t)
  }, [swState])

  // Optimistically write the new prefs into the query cache so the controlled
  // checkbox/select reflect the tap immediately. Without this the native control
  // flips, React re-renders it back to the (unchanged) server value before the
  // PUT round-trips, and the toggle appears dead — especially on iOS.
  const prefsMutation = useMutation({
    // Partial update: send only the field that changed. Re-posting the whole
    // object coupled the enable toggle to nudge_tz/nudge_hour validity, so a
    // stored timezone the server couldn't resolve 422'd the request and the
    // toggle could neither turn the nudge on nor off.
    mutationFn: (update: Partial<NotifPrefs>) =>
      api.put<NotifPrefs>('/notifications/preferences', update),
    onMutate: async (update) => {
      await queryClient.cancelQueries({ queryKey: ['notifications', 'preferences'] })
      const previous = queryClient.getQueryData<NotifPrefs>(['notifications', 'preferences'])
      if (previous) queryClient.setQueryData(['notifications', 'preferences'], { ...previous, ...update })
      return { previous }
    },
    onError: (_err, _update, context) => {
      if (context?.previous) {
        queryClient.setQueryData(['notifications', 'preferences'], context.previous)
      }
      setStatusMsg("Couldn't save — try again.")
      setTimeout(() => setStatusMsg(null), 3000)
    },
    onSuccess: () => {
      setStatusMsg('Saved')
      setTimeout(() => setStatusMsg(null), 2000)
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ['notifications', 'preferences'] })
    },
  })

  const handleToggleSubscription = async () => {
    if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
      setStatusMsg('Push notifications are not supported in this browser.')
      return
    }
    if (!vapidKey) {
      setStatusMsg('Push notifications are not configured on this server.')
      return
    }

    // Re-read live permission — iOS persists this at the OS level and it can
    // differ from the last-read state without any page reload.
    const live = 'Notification' in window ? Notification.permission : 'denied'
    if (live !== permissionState) setPermissionState(live)
    if (live === 'denied') {
      setStatusMsg('Notifications are blocked for this install. On iOS, remove Luma from your Home Screen and re-add it to reset, then tap Subscribe and choose Allow.')
      return
    }

    setPending(true)
    try {
      if (subscribed) {
        const reg = await navigator.serviceWorker.getRegistration()
        const sub = reg ? await reg.pushManager.getSubscription() : null
        if (sub) {
          const keys = sub.toJSON().keys ?? {}
          await api.post('/notifications/unsubscribe', {
            endpoint: sub.endpoint,
            p256dh: keys.p256dh ?? '',
            auth: keys.auth ?? '',
          })
          await sub.unsubscribe()
        }
        setSubscribed(false)
        prefsMutation.mutate({ nudge_enabled: false })
        return
      }

      // iOS requires Notification.requestPermission() to run inside the user
      // gesture — so prompt FIRST, before any slow await (SW resolution) that
      // would consume the transient activation and silently suppress the prompt.
      let permission: NotificationPermission = live
      if (permission === 'default') {
        permission = await Notification.requestPermission()
        setPermissionState(permission)
      }
      if (permission !== 'granted') {
        setStatusMsg('Notification permission denied. Remove Luma from your Home Screen and re-add it to try again.')
        return
      }

      setStatusMsg('Preparing background service…')
      let reg: ServiceWorkerRegistration
      try {
        reg = await getReadyRegistration()
      } catch (swErr) {
        setSwState('failed')
        setStatusMsg(swErr instanceof Error ? swErr.message : 'Background service error - close the app fully and try again.')
        return
      }
      setSwState('ready')

      const sub = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(vapidKey),
      })
      const keys = sub.toJSON().keys ?? {}
      await api.post('/notifications/subscribe', {
        endpoint: sub.endpoint,
        p256dh: keys.p256dh ?? '',
        auth: keys.auth ?? '',
        device_label: navigator.userAgent.slice(0, 80),
      })
      setSubscribed(true)
      setStatusMsg(null)
      prefsMutation.mutate({ nudge_enabled: true })
    } catch (err) {
      setStatusMsg(`Subscription failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      setPending(false)
    }
  }

  const isPushSupported = 'PushManager' in window && 'serviceWorker' in navigator
  const isBlocked = permissionState === 'denied'
  const swPreparing = swState !== 'ready' && swState !== 'failed'

  // The button is never gated on SW readiness — the click handler drives the SW
  // to ready itself — so it can't deadlock the way the old swState gate did.
  const buttonDisabled = !isPushSupported || pending
  const buttonLabel = pending ? 'Working…' : subscribed ? 'Unsubscribe' : 'Subscribe'

  return (
    <div className="glass settings-card" style={{ padding: 24 }}>
      <div style={{ marginBottom: 20 }}>
        <div className="eyebrow" style={{ marginBottom: 8 }}>Notifications</div>
        <p style={{ color: 'var(--fg-tertiary)', fontSize: 14, margin: 0 }}>
          Daily logging nudge and high-priority health alerts.
        </p>
      </div>

      {!isPushSupported && (
        <div style={{ padding: '12px 14px', background: 'rgba(251,113,133,0.08)', border: '1px solid rgba(251,113,133,0.22)', borderRadius: 8, fontSize: 13, color: 'var(--bad)', marginBottom: 16 }}>
          Push notifications require installing Luma as a PWA on a supported device.
        </div>
      )}

      {isBlocked && (
        <div style={{ padding: '12px 14px', background: 'rgba(251,113,133,0.08)', border: '1px solid rgba(251,113,133,0.22)', borderRadius: 8, fontSize: 13, color: 'var(--bad)', marginBottom: 16 }}>
          Notifications are blocked for this install. On iOS, the only way to reset is to <strong>remove Luma from your Home Screen and re-add it</strong>, then tap Subscribe and choose Allow.
        </div>
      )}

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 16, borderBottom: '1px solid var(--glass-edge)', marginBottom: 16 }}>
        <div>
          <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--fg-primary)', marginBottom: 2 }}>Enable push notifications</div>
          <div style={{ fontSize: 12, color: 'var(--fg-quiet)' }}>
            {subscribed ? 'This device is subscribed.' : 'Subscribe this device to receive nudges and alerts.'}
          </div>
        </div>
        <button
          onClick={handleToggleSubscription}
          disabled={buttonDisabled}
          className={`btn${pending ? ' animate-pulse' : ''}`}
          style={{
            padding: '8px 16px',
            fontSize: 12,
            background: subscribed ? 'rgba(251,113,133,0.12)' : 'rgba(14,165,233,0.15)',
            color: subscribed ? 'var(--bad)' : 'var(--sky-400)',
            border: `1px solid ${subscribed ? 'rgba(251,113,133,0.3)' : 'rgba(14,165,233,0.3)'}`,
            opacity: buttonDisabled ? 0.5 : 1,
          }}
        >
          {buttonLabel}
        </button>
      </div>

      {swPreparing && !subscribed && (
        <div style={{ marginBottom: 12, fontSize: 12, color: 'var(--fg-tertiary)' }}>
          {swStuck
            ? 'Background service is taking a while. You can still tap Subscribe — if it fails, fully close the app and reopen it.'
            : 'Preparing background service — subscribe now and it will activate automatically.'}
        </div>
      )}

      {subscribed && prefs && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
            <div>
              <div style={{ fontSize: 13, color: 'var(--fg-secondary)', marginBottom: 2 }}>Daily logging nudge</div>
              <div style={{ fontSize: 11, color: 'var(--fg-quiet)' }}>If you haven't logged by this hour, Luma will remind you.</div>
            </div>
            <input
              type="checkbox"
              checked={prefs.nudge_enabled}
              onChange={(e) => prefsMutation.mutate({ nudge_enabled: e.target.checked })}
              style={{ width: 16, height: 16, accentColor: 'var(--sky-400)', flexShrink: 0 }}
            />
          </label>

          {prefs.nudge_enabled && (
            <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end' }}>
              <label style={{ display: 'flex', flexDirection: 'column', gap: 6, flex: 1 }}>
                <span style={{ fontSize: 11, color: 'var(--fg-quiet)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Nudge time</span>
                <select
                  value={prefs.nudge_hour}
                  onChange={(e) => prefsMutation.mutate({ nudge_hour: Number(e.target.value) })}
                  className="field-input"
                  style={{ padding: '8px 10px', fontSize: 13, background: 'var(--glass-1)', border: '1px solid var(--glass-edge)', borderRadius: 8, color: 'var(--fg-primary)' }}
                >
                  {HOUR_OPTIONS.map((o) => (
                    <option key={o.value} value={o.value}>{o.label}</option>
                  ))}
                </select>
              </label>

              <label style={{ display: 'flex', flexDirection: 'column', gap: 6, flex: 1 }}>
                <span style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 11, color: 'var(--fg-quiet)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                  <span>Timezone</span>
                  <button
                    type="button"
                    onClick={() => {
                      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
                      if (tz && tz !== prefs.nudge_tz) prefsMutation.mutate({ nudge_tz: tz })
                      setLocalTz(null)
                    }}
                    style={{ background: 'none', border: 'none', padding: 0, fontSize: 10, letterSpacing: '0.06em', color: 'var(--sky-400)', cursor: 'pointer', textTransform: 'uppercase' }}
                  >
                    Detect
                  </button>
                </span>
                <input
                  type="text"
                  value={localTz ?? prefs.nudge_tz}
                  onChange={(e) => setLocalTz(e.target.value)}
                  onBlur={(e) => {
                    const tz = e.target.value.trim()
                    if (tz && tz !== prefs.nudge_tz) prefsMutation.mutate({ nudge_tz: tz })
                    setLocalTz(null)
                  }}
                  onKeyDown={(e) => { if (e.key === 'Enter') (e.target as HTMLInputElement).blur() }}
                  placeholder="America/New_York"
                  className="field-input"
                  style={{ padding: '8px 10px', fontSize: 13, background: 'var(--glass-1)', border: '1px solid var(--glass-edge)', borderRadius: 8, color: 'var(--fg-primary)' }}
                />
              </label>
            </div>
          )}

          <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
            <div>
              <div style={{ fontSize: 13, color: 'var(--fg-secondary)', marginBottom: 2 }}>Weekly recap</div>
              <div style={{ fontSize: 11, color: 'var(--fg-quiet)' }}>A Sunday-evening summary of your week.</div>
            </div>
            <input
              type="checkbox"
              checked={prefs.recap_enabled}
              onChange={(e) => prefsMutation.mutate({ recap_enabled: e.target.checked })}
              style={{ width: 16, height: 16, accentColor: 'var(--sky-400)', flexShrink: 0 }}
            />
          </label>

          <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
            <div>
              <div style={{ fontSize: 13, color: 'var(--fg-secondary)', marginBottom: 2 }}>High-priority health alerts</div>
              <div style={{ fontSize: 11, color: 'var(--fg-quiet)' }}>Push when a warning-level health insight fires. They still appear in-app.</div>
            </div>
            <input
              type="checkbox"
              checked={prefs.health_alerts_enabled}
              onChange={(e) => prefsMutation.mutate({ health_alerts_enabled: e.target.checked })}
              style={{ width: 16, height: 16, accentColor: 'var(--sky-400)', flexShrink: 0 }}
            />
          </label>
        </div>
      )}

      {statusMsg && (
        <div style={{ marginTop: 12, fontSize: 12, color: statusMsg.toLowerCase().includes('fail') || statusMsg.toLowerCase().includes('deny') || statusMsg.toLowerCase().includes('block') || statusMsg.toLowerCase().includes('not') || statusMsg.toLowerCase().includes('couldn') ? 'var(--bad)' : statusMsg.toLowerCase().includes('preparing') ? 'var(--fg-tertiary)' : 'var(--good)' }}>
          {statusMsg}
        </div>
      )}
    </div>
  )
}
